### ISSUE TITLE
[Feature Request] - Wiki style internal linking

### ISSUE THREAD

**Issue by BrendanThompson** [HappenApps/Quiver#654] opened 2016-07-28 04:10 UTC
It would be **AMAZING** if when one types `[[` you can start typing another note title and it will show a list that you can select from and then have an internal link. As I have many notes that I'd like to link between.

**Comment by notmgsk** [comment] 2016-08-02 18:17
Definitely. I was just thinking about this. Would be nice if you could link to specific sections of a note, but even just having top-level note linking/referencing would be great.

**Comment by ghost** [comment] 2016-12-08 08:48
+1

I would love to see org-mode style wiki links brought to quiver. Something like:

    [[title of note]]
    [[title of note|description]]

If the note exists, style the link blue, otherwise, style the link red (or whatever colors are determined by the theme in use).

On click -> if the note already exits, navigate to note. If thenote does not exist, prompt user to create it.

I would also love to see automatic link creation. So if "My awesome Note" already exists, typing "My Awesome Note" automatically links to this heading.

**Comment by brettz9** [comment] 2017-12-13 06:22
I agree that rather than being bothered by a list, it would be nice to just immediately style the colors if they exist or not. But if linking to other notes in other notebooks could benefit from a pop-up UI, perhaps a toolbar button could do this.

The whole word "wiki" means fast, and having to do it manually does not allow one to compose links and fill in new pages so quickly as with this method.

Btw, this appears to be a dupe of #170 (and a subset of #966).

**Closed as completed** 2020-05-11 05:14 UTC
