### ISSUE TITLE
iOS apps

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#207] opened 2015-10-21 14:17 UTC
Any plans for iOS apps?

I use quiver for keeping notes (that are written outside of the lecture) and would like for those notes to be available on my iPad (which I use during lecture). 

For this use-case it may not even be necessary for an iOS "app". Since quiver already uses iCloud for syncing, I could just have exports of my notes saved to iCloud. But this would be laborious having to re-export all my notes after a small change. Perhaps this could be an option... auto-exporting?

**Comment by ylian** [comment] 2015-10-21 20:44
An iOS app is under development. I already have a prototype that can preview notes, but more work needs to be done in syncing and editing. I will be focusing on the iOS app after Quiver 3.0 is out.

**Comment by ghost** [comment] 2015-10-22 09:19
Great to know! Money well spent.

**Comment by Strajk** [comment] 2015-10-22 13:25
Hey @ylian , I would totally appreciate first version even without editing, just viewing!

**Comment by ghost** [comment] 2015-10-22 13:26
Likewise.

**Comment by ylian** [comment] 2015-10-22 13:30
The bigger challenge is to get the notes onto the device, and keep them synced.

**Comment by aaronwolen** [comment] 2015-10-28 14:08
Exciting news!

**Comment by RoCry** [comment] 2015-11-12 02:17
If I could test the early version with TestFlight will be great. Thanks!

**Comment by ylian** [comment] 2015-11-12 10:18
Working on the iOS app right now. The TestFlight version has expired a long time ago. I am trying to get syncing working so it's actually usable.

**Comment by stevejordi** [comment] 2015-11-12 15:09
The problem is that you probably need two kinds of sync platforms: DropBox and iCloud for the AppStore released version.
A very good document ressource for help could be found here
https://www.objc.io/issues/10-syncing-data/

**Comment by ylian** [comment] 2015-11-12 18:47
@stevejordi Thanks for the link. It's helpful. Indeed I need to support at least Dropbox and iCloud Drive, probably Google Drive as well.

**Comment by marionava** [comment] 2015-11-16 23:02
Excellent news!! @ylian. Thanks!!

**Comment by X-G** [comment] 2015-12-01 12:39
exciting news! I'm looking forward!! @ylian

**Comment by helmut72** [comment] 2015-12-01 13:57
Please don't forget the ones who want to sync over an own WebDAV server. An own NAS or a running Owncloud is common for IT people. Dropbox, iCloud/Google Drive are no options.

**Comment by ylian** [comment] 2015-12-01 17:59
@helmut72 Thanks. I am aware of that. WebDAV support will be there.

**Comment by helmut72** [comment] 2015-12-01 18:44
Fantastic! Thank you!

**Comment by dinomite** [comment] 2015-12-02 19:12
As if you need more encouragement…just bought Quiver and I'll happily buy the iOS app to match when it's ready.

**Comment by JMichaelTX** [comment] 2015-12-03 01:16
> Working on the iOS app right now.

Great news!  :+1: 
I'm all for a Quiver iOS app, and would be glad to pay extra for it.

**Comment by ghost** [comment] 2015-12-03 09:30
Great to know!  I would be glad to pay extra for the first version even without editing, just viewing! And without Dropbox, just iCloud!

**Comment by ylian** [comment] 2015-12-03 15:49
I just set up a signup form for "Quiver for iOS" beta testing. The beta testing will start in early January, but feel free to sign up now: http://eepurl.com/bItzIv

**Comment by JMichaelTX** [comment] 2015-12-04 04:56
I'm in.  :+1:

**Comment by marionava** [comment] 2015-12-05 03:47
@ylian I already registered por Quiver for iOS.

**Comment by funcmike** [comment] 2015-12-24 13:09
@ylian Waiting for beta :) Quiver for ios = good bye evernote forever

**Comment by paultopia** [comment] 2016-01-16 18:41
Glad to hear there's an iOS beta coming!  One thought also: if there were a way to change the file naming scheme, it would be lots easier for people to just roll their own (e.g. using pythonista and Dropbox).  I've been thinking of doing that, but right now it would be a bit annoying, because in order to select and edit existing notes with the non-informative filenames, one would have to essentially download and cache every note.  Not sure what a good solution might be, but it would be cool to have one.

**Comment by fredrikaverpil** [comment] 2016-02-06 17:55
Lovely. Buying Quiver now and looking forward to the iOS version!

Perhaps it's "too soon" but if there were ever a Windows version, I'd be all set.

**Comment by espi** [comment] 2016-02-11 14:18
+1 for Owncloud

**Comment by helmut72** [comment] 2016-02-12 19:23
Is there any news about the Beta version? I just want to check how it works, how it looks like and if WebDAV is supported.
Because then I can start to transfer all my Apple Notes (now synced with own Imap server) to Quiver if the iOS version really fulfill what I expect.

**Comment by ylian** [comment] 2016-02-12 23:17
@helmut72 WebDAV will be supported in the first beta, as well as Dropbox and Google Drive. That's exactly why it's taking so long. In terms of functionalities, it's very similar to the Mac app. It works on iPhone/iPad, iOS7+.

![img_0021](https://cloud.githubusercontent.com/assets/984895/13023207/c25ed834-d1b4-11e5-9c2c-b21a1aecec39.jpg)

**Comment by ghost** [comment] 2016-02-15 21:06
Big +1 for Google Drive support!

**Comment by jfburr** [comment] 2016-02-15 22:09
Big +1 for Google Drive support also :)

**Comment by PhoenixWright** [comment] 2016-02-19 08:22
Is there any news on a date for the beta? It would be awesome to start using it even without every piece of functionality implemented.

**Comment by jariangibson** [comment] 2016-02-19 18:23
Any updates?

**Comment by ylian** [comment] 2016-02-19 18:25
Dealing with some technical challenges. Thanks for your patience.

**Comment by shajiquan** [comment] 2016-03-03 03:28
Any updates?

**Comment by ylian** [comment] 2016-03-03 14:09
First beta in a few days.

**Comment by benjamincharity** [comment] 2016-03-03 14:10
So pumped for this

**Comment by ylian** [comment] 2016-03-03 14:14
Just heads up that first beta will be read only, but at least you will be able to open a library from Dropbox/Google Drive/WebDAV and view all your notes on the go. I have got basic flow working with all three services, and just adding error handling stuff to make it more reliable.

**Comment by shajiquan** [comment] 2016-03-03 14:43
@ylian WOW, amazing. Ready for testing it.

**Comment by paulelms** [comment] 2016-03-03 15:03
@ylian OMG iCloud Drive not on the list?

**Comment by ylian** [comment] 2016-03-03 15:04
@paulelms It will come, just not in the first beta. It's a bit different from other cloud services.

**Comment by chenyanzhe** [comment] 2016-03-08 09:09
@ylian How to get the beta version?

**Comment by jeffkimbrel** [comment] 2016-03-10 07:24
Hi, I got my test flight link tonight, but it is expired. Can you update the expiration date? Looking forward to seeing the ios version in action!

**Comment by ylian** [comment] 2016-03-10 11:38
@jeffkimbrel You should have got another email from me. Basically TestFlight is still pointing to an old expired build, while the new build was submitted last night and should be approved today.

**Comment by tarr1124** [comment] 2016-03-10 11:56
Hi, my invitation code is expired too. I can't see any other e-mail from TestFlight. Please let me know if you have solution.
I'm looking forward to use iOS version!

**Comment by ylian** [comment] 2016-03-10 11:59
@tarr1124 As I said, TestFlight is still pointing to an old build, while the new build should be approved today.

**Comment by tarr1124** [comment] 2016-03-10 12:23
Sorry, it was my misunderstanding. I can't wait for it!

**Comment by benjamincharity** [comment] 2016-03-10 12:24
Any more testflight invites available? Would love to use/help in any way I can.

**Comment by ylian** [comment] 2016-03-10 12:27
@benjamincharity  Yeah, please sign up here: http://eepurl.com/bItzIv

**Comment by chenyanzhe** [comment] 2016-03-10 14:15
just got this when trying to connect Dropbox library

On 周四, 3月 10, 2016 at 8:27 下午, Yaogang Lian notifications@github.com wrote:
@benjamincharity [https://github.com/benjamincharity] Yeah, please sign up here: http://eepurl.com/bItzIv [http://eepurl.com/bItzIv]

—
Reply to this email directly or view it on GitHub
[https://github.com/HappenApps/Quiver/issues/207#issuecomment-194819163] .[https://github.com/notifications/beacon/AD90rVLp3Iy6xahB8cYGftKfWRbYbQ77ks5psA42gaJpZM4GTAab.gif]

**Comment by ylian** [comment] 2016-03-10 14:16
My bad. I will contact Dropbox right away.

Yaogang

**Comment by michaelnew** [comment] 2016-03-10 20:37
I'm having trouble connecting with WebDAV (I'm using ownCloud). I'm able to connect and see the root directory, but if I try to open anything it just shows up as an empty directory. I'm able to browse with other WebDAV navigator apps, so I don't think it's a problem on my end.

It's also displaying %20 rather than the space character.
![image3352](https://cloud.githubusercontent.com/assets/522101/13684062/e0aa93c2-e6be-11e5-95d6-6228113ae6a7.png)

**Comment by stevejordi** [comment] 2016-03-10 23:58
Great,
Looks very promising. I was able to import all my notes and they preview correctly.
Tried to create a new one, and type in a few test sentences.
Just a question: how do you create a new cell? There is no ctrl-return, etc...?

**Comment by ylian** [comment] 2016-03-11 02:31
@stevejordi Great. As I said in the test description, this first beta should be used as read-only. Note editing and creation are not ready yet.

**Comment by stevejordi** [comment] 2016-03-11 06:23
Ok thanks. I thought that they would just not be saved back. If not too complex, you should add some special characters to the keyboard, like tab, or markdown etc... frequently used symbols... :-)

**Comment by ylian** [comment] 2016-03-12 02:26
@mikenew12 Can you send me a test account for your WebDAV server? Thanks. My email: ylian@happenapps.com

**Comment by ylian** [comment] 2016-03-12 02:28
Closing this. There is a new tracker for iOS-specific issues: https://github.com/HappenApps/Quiver-iOS/issues

**Closed as completed by ylian** 2016-03-12 02:28 UTC
