### ISSUE TITLE
Code cell is not saved when only deleting content, when in Vim mode

### ISSUE THREAD

**Issue by joaopimentel** [HappenApps/Quiver#37] opened 2015-02-13 18:19 UTC
When using Vim key binding for code cells, a code cell doesn't seem to be saved when the only changes are deletion of content (deleting lines or individual characters).
Opening another note and then returning to the first shows the code cell with no changes.

If content is added the cell is correctly saved. If content is deleted but new content is inserted, it also saves fine.

In ACE mode, this problem doesn't occur.

**Comment by ylian** [comment] 2015-02-13 19:24
Thanks. I can reproduce the issue. Will fix in v2.1.1.

**Comment by ylian** [comment] 2015-03-03 22:43
Fixed in 2.1.1.

**Closed as completed by ylian** 2015-03-03 22:43 UTC

**Comment by ylian** [comment] 2015-03-04 01:14
Note that I had to retract 2.1.1 due to a separate issue. Please wait for 2.1.2 to verify this fix.
