### ISSUE TITLE
Copy Paste Broken

### ISSUE THREAD

**Issue by nwaywood** [HappenApps/Quiver#42] opened 2015-02-19 01:41 UTC
Copy Paste only works in text cells, not in code, markdown or latex cells. It does work if I copy text from a text cell and paste it into a markdown cell but if I try and copy paste text written in the markdown cell itself it doesnt work.

OS: OSX Yosemite
Version: 2.1 (8), Full version

**Comment by ylian** [comment] 2015-02-19 02:30
This is a weird bug. Got a report of this issue for Quiver 2.0, but I have never been able to reproduce it. I would greatly appreciate it if you can think of anything unusual about your setup.

**Comment by ylian** [comment] 2015-02-19 04:07
Are you using a clipboard manager app?

**Comment by catesandrew** [comment] 2015-02-20 23:35
I'm experiencing the same issue. I'm running [Get Plain Text](http://zipzapmac.com), [LaunchBar](http://www.obdev.at/products/launchbar/index.html) and [iClip](http://www.irradiatedsoftware.com/). These running apps could also be the source Fantastical, Witch, google-drive, Yoink, Dash, BetterSnapTool, CloudApp, Growl, Unclutter, but I doubt it.

quitting iClip, launchbar, and get plain text didn't fix the bug. 

it probably has to be a bug in the ace editor.
- https://github.com/ajaxorg/ace/issues/1842

Or a small issue where ace clipboard is not shuffling the contents to/from the host.

idk, but its something with ace

I'm also running home brew

**Comment by ylian** [comment] 2015-02-21 03:28
Anyone in the Toronto area who can reproduce this issue? Would be of great help, thanks.

**Comment by ylian** [comment] 2015-02-21 14:11
Can anyone try this build? Just double click to open. Don't overwrite the AppStore version, otherwise you won't get automatic updates. Thanks.

Update: Link removed now that the issue is found.

**Comment by catesandrew** [comment] 2015-02-21 14:29
+1 That download link fixes the issue. I'm able to copy to clipboard once again!

**Comment by ylian** [comment] 2015-02-21 14:32
Awesome. Indeed it's related to the ticket you mentioned. I changed `BROKEN_SETDATA` to `true`, which doesn't use the native clipboard (`window.clipboardData`) but falls back to Ace's own implementation. I will run further testing on all OS versions.

**Comment by nwaywood** [comment] 2015-02-22 22:48
I didnt get a chance to try out the build you posted here before you removed it so I cant confirm whether it fixes the problem for me or not. I am not using iClip or any other clipboard manager app

**Comment by ylian** [comment] 2015-02-22 23:07
No problem. I am quite sure it's fixed. Already submitted v2.1.1.

**Comment by ylian** [comment] 2015-03-03 22:44
Fixed in 2.1.1.

**Closed as completed by ylian** 2015-03-03 22:44 UTC

**Comment by ylian** [comment] 2015-03-04 01:14
Note that I had to retract 2.1.1 due to a separate issue. Please wait for 2.1.2 to verify this fix.

**Comment by ylian** [comment] 2016-07-10 18:43
Could anyone on the list try a new build? I am fixing another bug but the fix might cause regression on this one.

https://dl.dropboxusercontent.com/u/3445731/Quiver-cmd-x-test.zip

Try to copy from a code cell or Markdown cell and see if it works. Thanks.

**Comment by pmackay** [comment] 2017-05-12 08:13
@ylian did this last build you posted ever get tested? I've only just recently downloaded Quiver (Version 3.0.6 (99)) and found the Copy Cell function doesnt work. Which is a shame because it feels like its an important part of really taking advantage of the cells functionality. Any help would be much appreciated :)

I do generally run Copy'm Paste but quitting it didnt help.
