### ISSUE TITLE
Suggestion: Nested Notebooks

### ISSUE THREAD

**Issue by nwaywood** [HappenApps/Quiver#63] opened 2015-03-10 04:36 UTC
Sometimes it would be very useful to have one extra 'layer' to notebooks/notes. i.e. Allow a notebook to contain a group a notebooks which can then contains notes

**Comment by LeonardoGentile** [comment] 2015-03-10 10:09
This is already discussed in #2

**Comment by ylian** [comment] 2015-03-10 12:14
Closed as a duplicate of #2.

**Closed as completed by ylian** 2015-03-10 12:14 UTC
