### ISSUE TITLE
Automator workflow issues

### ISSUE THREAD

**Issue by paulelms** [HappenApps/Quiver#362] opened 2016-01-17 08:01 UTC
I’m using Markdown Service Tools, but it does not work with Quiver: http://brettterpstra.com/projects/markdown-service-tools/

> The Markdown Service Tools are a collection of OS X Services designed to make writing Markdown text that much easier. Services work in any Cocoa-based application

I recorded a short video demonstration: http://take.ms/uHNcu

Expected behavior: list ordering should be fixed, but nothing happens. In other text editors it works as expected. Seems like all automator workflows work in Quiver with errors.

Other demo: http://take.ms/q6BzH

Looks like «Searchlink» workflow searched for «?» instead of «Firefox».

**Comment by paulelms** [comment] 2016-01-17 08:04
P.S. Same behavior in App Store version and 3.0.1 beta.

**Comment by ylian** [comment] 2016-01-17 11:26
Duplicate of #163. It's an issue with the Ace editor. I haven't got time to fix Ace bugs (it will take me a few weeks to understand the codebase), but hopefully soon.

**Closed as completed by ylian** 2016-01-17 11:26 UTC
