### ISSUE TITLE
Require sensible means to resolve conflict results from sync using Dropbox.

### ISSUE THREAD

**Issue by KimMichaelJones** [HappenApps/Quiver#811] opened 2017-03-25 13:07 UTC
I am using Dropbox to sync across Macs. 
Steps:
  I edit a notebook and leave Quiver open on my MacBook
  Later edit the same notebook on my iMac.
  Later yet, return to the MacBook and I receive a message stating the note been changed on disk. 
No information is provided as to what the conflict includes. The only options are to overwrite (discard edit  on iMac) or discard (discard edit on MacBook). Not asking/expecting full merge functionality, but even Dropbox allows me to view both version and manually clean it up.
As a result I am constantly trying to remember to close Quiver when I end a session on each Mac. Feels kind of like working in Windows in 1990. Ugh.

**Comment by ylian** [comment] 2017-03-25 22:55
This is mostly caused by a bug. Will fix when refactoring the model layer. Coming up next.

**Comment by KimMichaelJones** [comment] 2017-03-25 23:18
That's great, much appreciated!

**Comment by ylian** [comment] 2018-11-27 17:22
Fixed in 3.2.1. The dreadful "contents have changed on disk" dialog is history. Quiver now automatically reloads the opened notes to the latest version.

**Closed as completed by ylian** 2018-11-27 17:22 UTC
