### ISSUE TITLE
[Feature Request] Notebook Categories for easier visual mapping

### ISSUE THREAD

**Issue by Galactix** [HappenApps/Quiver#540] opened 2016-03-30 17:36 UTC
Just found Quiver a few weeks ago and love it, design, ease of use, etc. I also know it's a work in progress so I understand that issues are resolved in order of importance.

But I would like to request a feature that would make organizing notebooks much easier. The ability to separate notebooks into different sections for faster navigation. Right now I put notebooks I use daily under Shared so I can reach them faster, I have also inserted emoji icons on some notebook titles to keep them at the top. 

For the past few years I have used TapForms for my most important documents, it's great as a database app but not as a notebook, too many steps to input basic text. But it does provide categories that a user can organize their notebooks into. Great for visually separating notebooks for quick discovery.

Thanks again for the great app and I hope my request can find it's way onto a list for future feature improvements.

![screen shot 2016-03-30 at 10 32 18 am](https://cloud.githubusercontent.com/assets/11774181/14151525/25d91bfe-f663-11e5-8080-a81df2f7967f.png)

**Comment by ylian** [comment] 2016-03-30 19:55
This feature is coming in 3.1. Close as a duplicate of #2.

**Closed as completed by ylian** 2016-03-30 19:55 UTC

**Comment by Galactix** [comment] 2016-04-06 20:43
Groovy, and thanks for the great product.
