### ISSUE TITLE
there are spaces at the end of line in the markdown style

### ISSUE THREAD

**Issue by ecchanger** [HappenApps/Quiver#261] opened 2015-12-02 00:41 UTC
there are spaces at the end of line in the markdown style

**Comment by ylian** [comment] 2015-12-02 00:44
Can you take a screenshot? I don't see any spaces in Markdown cells.

**Comment by ylian** [comment] 2015-12-11 21:01
I assume this is a duplicate of #249. If not, please reopen and clarify.

**Closed as completed by ylian** 2015-12-11 21:01 UTC
