### ISSUE TITLE
Custom Preview style (css) is not applied

### ISSUE THREAD

**Issue by LaurentFough** [HappenApps/Quiver#53] opened 2015-02-23 20:38 UTC
I’ve successfully edited the editor css, saved and viewed the changes.
In trying to the do the same to the preview css, the changes are not applied.

**Notes:**
_\- have tried different fonts, to no avail_
_\- have tried quoted/unquote font declarations_

**Changes:**
- applied custom font-family
- applied custom font-size

**New Preview css:**

``` /**
    * Text Cell
    */

    .text-cell {
      font-family: Avenir Next;
      font-size: 13px;
    }

    /**
    * Code Cell
    */

    .code-cell .editor {
      font: PragmataPro;
      font-size: 13px;
      line-height: 1.2;
    }

    /**
    * Markdown Cell
    */

    .markdown-cell {
      font-family: Avenir Next;
      font-size: 13px;
    }

    /*
    * LaTeX Cell
    */

    .latex-cell {
      font-family: Avenir Next;
      font-size: 13px;
    }`
```

**Comment by ylian** [comment] 2015-02-23 22:35
Just pasted your CSS into my preview.css, and it works fine. Please reset the preview CSS, then apply changes one by one with the preview open. You should be able to see the change as you apply them. Might be some little things messing up the CSS.

**Comment by ylian** [comment] 2015-03-03 22:46
Close this since no further information is provided. Please reopen if you can reproduce.

**Closed as completed by ylian** 2015-03-03 22:46 UTC
