### ISSUE TITLE
[Bug] Text services not work in cells except text cell

### ISSUE THREAD

**Issue by canmor** [HappenApps/Quiver#667] opened 2016-08-09 07:49 UTC
I can't run "lookup", "search with google", "services" on selected text in various type of cells except Text Cell, look at the screenshot,
<img width="564" alt="2016-08-09 3 20 51" src="https://cloud.githubusercontent.com/assets/2331833/17508670/b0e3d084-5e48-11e6-86ae-8ccc3fd29a4d.png">
 you will find that "Look Up" menu item shows the the selected text is empty. I'd try and found that neither of Markdown Cell, Code Cell, LaTex Cell and Diagram Cell works, only Text Cell works fine.

**Comment by canmor** [comment] 2016-08-10 10:15
@ylian

**Comment by ylian** [comment] 2016-08-10 10:20
Yes it's a bug with the Ace editor. I am in the process of replacing the Markdown editor, so this will be fixed together with many other Markdown-related issues.

**Comment by ylian** [comment] 2016-08-10 10:21
Closed as a duplicate of #284.

**Comment by canmor** [comment] 2016-08-10 10:22
OK, got it. Thank you!

**Closed as completed by ylian** 2016-08-10 10:21 UTC
