### ISSUE TITLE
Same note duplicated many times (sync with Dropbox)

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#22] opened 2015-01-22 09:31 UTC
Opening a notebook I noticed that the same note was duplicated multiple times (around 10 more or less).
I quit the app and on reopening the note was not duplicated.

I'm syncing my notes with dropbox, so maybe quiver was considering multiple revisions of the same note as different notes?

**Comment by ylian** [comment] 2015-01-22 13:56
It's interesting to know that reopening the app removes the duplicates. The self-recovering capability I built into Quiver seems to work. :) 

This means that the duplicate notes have the same ID. Theoretically they should never be duplicated since I use a NSSet for the notes in a notebook, and a set doesn't allow duplicates. Very interesting. I will dig into it.

**Comment by ylian** [comment] 2015-01-22 14:00
Hmm, although I use a set for notes, note objects might still be created multiple times for the same ID, and a set won't prevent that. I will check the syncing logic.

**Comment by LeonardoGentile** [comment] 2015-01-23 10:16
This did not work on the other machine synced with dropbox, I see those multiple duplicates of the same notes (more than one) and a quit-and-reopen did not work tough.

So in the machine A(that produced the notes) the problem was solved, the machine B (reading the notes) the problem persists

A hint: the notes have different creation times and dates but apparently they look identical

**Comment by ylian** [comment] 2015-01-23 14:15
Can you check the note ids? Right click on a note, show in finder, then open meta.json in a text editor. I wonder if those duplicate notes share the same id.

**Comment by ylian** [comment] 2015-01-23 19:54
I wonder if it's because Dropbox has created conflicted copies of the same note during syncing. Can you check the filenames of those duplicate notes? Thanks. Right click and show in finder.

**Comment by LeonardoGentile** [comment] 2015-01-24 01:07
Hello, 
right click / show in finder on the three duplicates takes me always to the same file, so of course their uuid in meta.json is always the same. 

In the screenshot you can see that even if quiver takes me to the same file some of the duplicated notes have different update date.

I hope it can help

![image](https://cloud.githubusercontent.com/assets/412061/5885459/7e94e132-a36d-11e4-9570-9ded190df39d.png)

**Comment by LeonardoGentile** [comment] 2015-01-24 01:09
Another thing, the note count on the Notebook title (on the sidebar) is taking into account the duplicated. so instead of having for example a count of 2 notes it shows a count of 6

**Comment by ylian** [comment] 2015-01-24 04:27
Thanks. This helps.

**Comment by ylian** [comment] 2015-01-24 04:29
Just one more question. When you right click the note and show in finder, does the notebook folder have 2 .qvnote files or 6? Any filenames like *** (conflicted copy)? I just want to make sure it's not Dropbox creating conflicted copies of note files.

**Comment by LeonardoGentile** [comment] 2015-01-24 11:57
there are the (supposed) correct number of notes that means 7 without the duplicates. The app says that there are 11 because it counts the duplicates. 
No names containing "conflicted copy"

**Comment by ylian** [comment] 2015-01-24 15:31
Appreciate it. This helps.

**Comment by LeonardoGentile** [comment] 2015-01-28 19:57
The only workaround was to change the library so that Quiver started to re-use its default on. Then I setup again the synced dropbox library and the duplicated items were gone

**Comment by ylian** [comment] 2015-01-29 21:09
I think I found what's causing the bug. The file change events can sometimes be triggered several times, and the logic I implemented there didn't de-duplicate those events.

Let me know if you still have a way to reproduce this issue so I can send you a beta build.

**Comment by ylian** [comment] 2015-01-30 23:23
Tested with another user's data. I am sure it's fixed now. Submitting v2.1 tonight.

**Comment by ylian** [comment] 2015-02-10 05:09
Fixed in Quiver 2.1.

**Closed by ylian** 2015-02-10 05:09 UTC
