### ISSUE TITLE
Links to local PDF files cannot be opened by Quiver

### ISSUE THREAD

**Issue by markowiec** [HappenApps/Quiver#146] opened 2015-07-12 15:54 UTC
Added couple of links in text cells to locally stored pdf files. When I click on the link I receive "Program Quiver is not authorized to open xxx.pdf file" error. To overcome that I need to manually select every single file in Finder and in "Open i program" select (and insist on that selection) Quiver - then it's default pdf reader for that particular file. Files have myusername:staff ownership and 755 permissions.

**Comment by ylian** [comment] 2015-07-12 17:40
Duplicate of #88. You can use the beta build in that ticket for now, while I finish up the next update.

**Closed as completed by ylian** 2015-07-12 17:40 UTC

**Comment by markowiec** [comment] 2015-07-12 19:45
Thank you for the reply. I checked the beta as you advised but unfortunately it didn't solved my problem. The attached screen shot is in Polish but shows the problem I described. The message says: Program Quiver 2.2b27.app doesn't have permission to open "....pdf".

<img width="538" alt="screen shot 2015-07-12 o 21 35 07" src="https://cloud.githubusercontent.com/assets/7799161/8639592/e5f3822e-28de-11e5-824c-4eb85bfeeca5.png">

**Comment by ylian** [comment] 2015-07-12 21:37
You have to drag the link into Quiver at least once to get around the sandbox limitation. You can drag a top folder to Quiver once, then it will automatically grant permissions to all the files within. Note that this only works if you use the beta build in that ticket.

**Comment by markowiec** [comment] 2015-07-12 21:50
That's right! I've learned that - now it works well - thanks a lot for help ! Looking forward for final updated version.
