### ISSUE TITLE
LaTex inside a markdown cell is not rendered properly when using _

### ISSUE THREAD

**Issue by alanzchen** [HappenApps/Quiver#319] opened 2015-12-21 14:57 UTC
Try this inside a markdown cell. On the source side, the `1=p(y)y` is italic. Markdown syntax should be disabled inside an inline LaTex.

```
$\pi_1=p(y)y_1-c(y_1)$
```

You can take a look at how another app, Archimedes, handles this. It has a LaTex highlighting mixed with Markdown syntax highlighting.

**Comment by ylian** [comment] 2015-12-21 15:53
Yes, this is an issue inside the editor. Duplicate of #209.

**Closed as completed by ylian** 2015-12-21 15:53 UTC

**Comment by alanzchen** [comment] 2015-12-22 01:09
Sorry about that. I searched LaTex but no result so I suspect nobody talked about this.
