### ISSUE TITLE
vim mode touch bar blink

### ISSUE THREAD

**Issue by xg-wang** [HappenApps/Quiver#955] opened 2017-09-12 23:20 UTC
macOS 10.12.5
13-inch, 2016, Four Thunderbolt 3 Ports

In vim mode, input triggers touch bar blink.

**Comment by zachkirsch** [comment] 2017-09-17 23:05
Seems to be a dupe of #788

**Comment by ylian** [comment] 2017-11-09 08:53
Fixed in 3.1.1.

**Closed as completed by ylian** 2017-11-09 08:53 UTC
