### ISSUE TITLE
Quiver library not opened on startup

### ISSUE THREAD

**Issue by emanuel-lundman** [HappenApps/Quiver#349] opened 2016-01-11 11:45 UTC
Hi, for me the library after move to dropbox folder isn't opened automatically on startup.
If I go to preferences > sync and click Open another library the file picker is in the right folder and I can pick the library and it opens my notes. If I restart I have to to this all over again.

**Comment by ylian** [comment] 2016-01-11 12:47
That's weird. Is it possible to do screen sharing via Google Hangout? It would be much easier to sort this out with screen sharing. Thanks. I am online for the next hour and any time after lunch (eastern time).

**Comment by bparvitte** [comment] 2016-01-15 14:29
Same problem for me on my desktop computer. On my macbook air everything is fine !

**Comment by ylian** [comment] 2016-01-15 14:32
@bparvitte Can you try these two builds with the Console app open, and let me know the log in the console?

https://dl.dropboxusercontent.com/u/3445731/Quiver-debug1.zip

https://dl.dropboxusercontent.com/u/3445731/Quiver-debug2.zip

These builds will log some debugging info when you open the app.

Thanks.

**Comment by bparvitte** [comment] 2016-01-15 15:25
I tried both builds  :
- Launch Quiver, Open Another Library, then stop Quiver after import is 
  complete.
- Launch Quiver again.

Thanks

On 15 Jan 2016, at 15:32, Yaogang Lian wrote:

> @bparvitte Can you try these two builds with the Console app open, and 
> let me know the log in the console?
> 
> https://dl.dropboxusercontent.com/u/3445731/Quiver-debug1.zip
> 
> https://dl.dropboxusercontent.com/u/3445731/Quiver-debug2.zip
> 
> Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HappenApps/Quiver/issues/349#issuecomment-171975595

15/01/2016 14:55:22,696 sandboxd[180]([2452]) Quiver(2452) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 14:55:22,747 sandboxd[180]([2452]) Quiver(2452) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 14:55:22,797 sandboxd[180]([2452]) Quiver(2452) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 14:55:22,849 sandboxd[180]([2452]) Quiver(2452) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 14:56:20,188 sandboxd[180]([2531]) Quiver(2531) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 14:56:20,215 sandboxd[180]([2531]) Quiver(2531) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 14:56:20,240 sandboxd[180]([2531]) Quiver(2531) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 14:56:20,265 sandboxd[180]([2531]) Quiver(2531) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:09:46,643 sandboxd[180]([3654]) Quiver(3654) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:09:46,669 sandboxd[180]([3654]) Quiver(3654) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:09:46,692 sandboxd[180]([3654]) Quiver(3654) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:09:46,715 sandboxd[180]([3654]) Quiver(3654) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:19:10,839 sandboxd[180]([4399]) Quiver(4399) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:19:10,865 sandboxd[180]([4399]) Quiver(4399) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:19:10,889 sandboxd[180]([4399]) Quiver(4399) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:19:10,000 kernel[0]   Sandbox: Quiver(4399) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:19:10,000 kernel[0]   Sandbox: Quiver(4399) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:19:10,923 sandboxd[180]([4399]) Quiver(4399) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:19:10,974 sandboxd[180]([4399]) Quiver(4399) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:19:11,000 sandboxd[180]([4399]) Quiver(4399) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:19:11,091 sandboxd[180]([4399]) Quiver(4399) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:19:11,114 sandboxd[180]([4399]) Quiver(4399) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:20:00,000 kernel[0]   Sandbox: Quiver(4450) deny(1) file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:20:00,000 kernel[0]   Sandbox: Quiver(4450) deny(1) file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:20:00,000 kernel[0]   Sandbox: Quiver(4450) deny(1) file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:20:00,000 kernel[0]   Sandbox: Quiver(4450) deny(1) file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:20:10,088 com.apple.xpc.launchd[1](com.happenapps.Quiver.352352[4450]) Service exited due to signal: Segmentation fault: 11
15/01/2016 15:20:11,619 ReportCrash[4526]   Saved crash report for Quiver[4450] version 3.0 (66) to /Network/Servers/sla.gsma.lan/Users/bertrand/Library/Logs/DiagnosticReports/Quiver_2016-01-15-152011_sla-gsma-lan.crash
15/01/2016 15:20:13,546 sandboxd[180]([4530]) Quiver(4530) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:20:13,554 sandboxd[180]([4530]) Quiver(4530) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:20:13,579 sandboxd[180]([4530]) Quiver(4530) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:20:13,000 kernel[0]   Sandbox: Quiver(4530) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:20:13,000 kernel[0]   Sandbox: Quiver(4530) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:20:13,603 sandboxd[180]([4530]) Quiver(4530) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:20:13,628 sandboxd[180]([4530]) Quiver(4530) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:20:13,651 sandboxd[180]([4530]) Quiver(4530) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:20:13,675 sandboxd[180]([4530]) Quiver(4530) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:20:13,700 sandboxd[180]([4530]) Quiver(4530) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:21:20,969 Quiver[4530]    Layout still needs update after calling -[SidebarRowView layout].  SidebarRowView or one of its superclasses may have overridden -layout without calling super. Or, something may have dirtied layout in the middle of updating it.  Both are programming errors in Cocoa Autolayout.  The former is pretty likely to arise if some pre-Cocoa Autolayout class had a method called layout, but it should be fixed.
15/01/2016 15:24:14,000 kernel[0]   Sandbox: Quiver(4940) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:24:14,000 kernel[0]   Sandbox: Quiver(4940) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:24:14,942 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:24:14,966 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:24:14,000 kernel[0]   Sandbox: Quiver(4940) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:24:14,000 kernel[0]   Sandbox: Quiver(4940) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:24:14,989 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:24:15,013 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:24:15,038 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:24:15,064 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:30:36,493 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Documents/Enseignement/UFR Sciences/M2 - NOA - PH0903 Lasers/Fig3_2.png
15/01/2016 15:30:47,853 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Dropbox/Notes/Reference/SignauxBruts.pdf
15/01/2016 15:30:47,873 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Dropbox/Notes/Reference/EffetCorrectionTempKn.pdf
15/01/2016 15:30:47,884 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Dropbox/Notes/Reference/FitLorAc442ExpAetB.pdf
15/01/2016 15:30:58,000 kernel[0]   Sandbox: Quiver(4940) deny(1) file-read-data /Users/bertrand/Documents/Recherche/Communications/Posters et Oraux/2014 - Comsol Cambridge/Poster/CambridgeJo.pdf
15/01/2016 15:30:58,000 kernel[0]   Sandbox: Quiver(4940) deny(1) file-read-data /Users/bertrand/Documents/Recherche/Communications/Posters et Oraux/2014 - Comsol Cambridge/Poster/CambridgeJo2.pdf
15/01/2016 15:30:58,283 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Documents/Recherche/Communications/Posters et Oraux/2014 - Comsol Cambridge/Poster/20131119_152116.jpg
15/01/2016 15:30:58,296 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Documents/Recherche/Communications/Posters et Oraux/2014 - Comsol Cambridge/Poster/fig2.tiff
15/01/2016 15:30:58,307 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Documents/Recherche/Communications/Posters et Oraux/2014 - Comsol Cambridge/Poster/Capture d’écran 2014-08-07 à 09.10.28.png
15/01/2016 15:30:58,319 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Users/bertrand/Documents/Recherche/Communications/Posters et Oraux/2014 - Comsol Cambridge/Poster/CambridgeAv442_FRes.pdf
15/01/2016 15:37:44,969 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Applications/MailMate.app/Contents
15/01/2016 15:37:44,979 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Applications/MailMate.app/Contents/Resources
15/01/2016 15:37:44,991 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Applications/MailMate.app/Contents/MacOS/MailMate/..namedfork/rsrc
15/01/2016 15:37:45,001 sandboxd[180]([4940]) Quiver(4940) deny file-read-data /Applications/MailMate.app/Contents/Resources
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:43:40,000 kernel[0]   Sandbox: Quiver(6806) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:44:42,623 Quiver[6806]    is stale? 0
15/01/2016 15:44:42,623 Quiver[6806]    fileURL: (null)
15/01/2016 15:44:42,623 Quiver[6806]    Loading bookmark error: The file couldn’t be opened.
15/01/2016 15:44:55,884 sandboxd[180]([6806]) Quiver(6806) deny appleevent-send info.eurocomp.timinghelper

15/01/2016 15:47:34,000 kernel[0]   Sandbox: Quiver(7053) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:47:34,000 kernel[0]   Sandbox: Quiver(7053) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:47:34,750 sandboxd[180]([7053]) Quiver(7053) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:47:34,774 sandboxd[180]([7053]) Quiver(7053) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:47:34,798 sandboxd[180]([7053]) Quiver(7053) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:47:34,822 sandboxd[180]([7053]) Quiver(7053) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:47:34,903 sandboxd[180]([7053]) Quiver(7053) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:47:34,927 sandboxd[180]([7053]) Quiver(7053) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:47:35,001 sandboxd[180]([7053]) Quiver(7053) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:47:35,028 sandboxd[180]([7053]) Quiver(7053) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:48:06,736 Quiver[7053]    is stale? 0
15/01/2016 15:48:06,736 Quiver[7053]    fileURL: (null)
15/01/2016 15:48:06,737 Quiver[7053]    Loading bookmark error: The file couldn’t be opened.

15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:55:43,000 kernel[0]   Sandbox: Quiver(7688) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 15:55:57,206 Quiver[7688]    is stale? 0
15/01/2016 15:55:57,206 Quiver[7688]    fileURL: (null)
15/01/2016 15:55:57,206 Quiver[7688]    Loading bookmark error: The file couldn’t be opened.
15/01/2016 15:56:10,000 kernel[0]   Sandbox: Quiver(7688) deny(1) appleevent-send info.eurocomp.timinghelper

15/01/2016 16:02:26,000 kernel[0]   Sandbox: Quiver(8163) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 16:02:26,000 kernel[0]   Sandbox: Quiver(8163) deny(1) file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Inbox.qvnotebook/meta.json
15/01/2016 16:02:26,806 sandboxd[180]([8163]) Quiver(8163) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter
15/01/2016 16:02:26,830 sandboxd[180]([8163]) Quiver(8163) deny file-read-data /Applications/MailMate.app/Contents/Library/Spotlight/MailMateSpotlight.mdimporter/Contents
15/01/2016 16:02:26,854 sandboxd[180]([8163]) Quiver(8163) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter
15/01/2016 16:02:26,878 sandboxd[180]([8163]) Quiver(8163) deny file-read-data /Users/bertrand/Library/PreferencePanes/Default Folder X.prefPane/Contents/Resources/Default Folder X Helper.app/Contents/Library/Spotlight/OpenMetaSpotlight.mdimporter/Contents
15/01/2016 16:02:26,987 sandboxd[180]([8163]) Quiver(8163) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 16:02:27,015 sandboxd[180]([8163]) Quiver(8163) deny file-read-data /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary
15/01/2016 16:02:27,049 sandboxd[180]([8163]) Quiver(8163) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 16:02:27,058 sandboxd[180]([8163]) Quiver(8163) deny file-write-unlink /Users/bertrand/Dropbox/Quiver/Quiver.qvlibrary/Trash.qvnotebook/meta.json
15/01/2016 16:03:10,208 Quiver[8163]    is stale? 0
15/01/2016 16:03:10,208 Quiver[8163]    fileURL: (null)
15/01/2016 16:03:10,208 Quiver[8163]    Loading bookmark error: The file couldn’t be opened.

**Comment by ylian** [comment] 2016-01-15 18:42
@bparvitte This is very helpful. The log confirmed that the library can't be opened due to "loading bookmark error". But I need a bit more help to figure out why this is happening. If you have 10 mins to spare, we can screen share via Google Hangout, and that would help me immensely. I am online for the next 10 hours.

**Comment by ylian** [comment] 2016-01-22 21:02
Figured it out. The fix is coming in 3.0.1.

**Comment by ylian** [comment] 2016-02-09 01:09
Fixed in 3.0.1.

**Closed as completed by ylian** 2016-02-09 01:09 UTC
Labels: scheduled for release
