### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#221] opened 2015-10-28 17:22 UTC
This is not a bug report per se, more of a wish list.

There are a LOT of language options for the code cell. For some reason, the default language seems to be C++ and I am not able to change it. Personally I am only concerned with max 4 or 5. Would be nice maybe to somehow have a prefs section for languages. There I could select which languages I actually want to enable (eg, show up) and maybe the possibility to set a default as opposed to C++.

Thanks.

v3.0.12

**Comment by ylian** [comment] 2015-10-28 19:28
The default language is automatically set to the language of the last code cell you clicked on. If that's not the case for you, let me know.

Hiding unused languages is planned for Quiver 3.1. Duplicate of #5.

**Comment by pentool** [comment] 2015-10-28 19:54
Ah, I see. Thanks.

**Closed as completed** 2015-10-28 20:02 UTC
