### ISSUE TITLE
"Lookup" and "Search" context menus work only with "Text" cells

### ISSUE THREAD

**Issue by Julien-Bernard** [HappenApps/Quiver#526] opened 2016-03-21 12:08 UTC
Hi,

With some content selected, we can usually right-click and use "**Lookup**" or "**Search with Google**" options. This is working perfectly well with "**Text**" cells, but doesn't work with others ("**Code**", "**Markdown**", etc).

Thanks,
Julien

**Comment by ylian** [comment] 2016-03-21 13:15
Duplicate of #284.

**Closed as completed by ylian** 2016-03-21 13:15 UTC
