### ISSUE TITLE
Lost entire note

### ISSUE THREAD

**Issue by PatrickF1** [HappenApps/Quiver#1246] opened 2018-12-20 19:49 UTC
Steps to reproduce
1. Double clicked on a note to open it up in its own window
2. Made it full screen
3. Did lots of work for an hour, writing in Markdown
4. Tried to preview the note in Markdown. Preview was empty.
5. Confused, I closed the window and navigated to the note in the main app window.
7. OMG the note is empty.
8. I check the filesystem and see that the note I was editing is indeed empty
9. I check the file's version history on Dropbox. It shows that the note didn't get updated at all while I was editing it.

Sounds like editing a note in its own window doesn't sync the changes or something?
And do you know of a way to possibly recover my work?

**Comment by arisc097** [comment] 2018-12-23 03:48
Lost everything today. Out of nowhere the sync / backup folder points to some other location. Note is empty. New path /Users/<user>/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary. Old path used to be under Documents.

**Comment by ylian** [comment] 2018-12-23 13:47
@arisc097 Your issue is different. It is likely due to having multiple versions of Quiver on your system. You can simply find your real library under Documents, and double click on it to open.

**Comment by ylian** [comment] 2018-12-23 13:49
@patrickf3139 Editing a note in its own window usually works fine. If you could reproduce this, please let me know. That will help greatly.

**Comment by waz0wski** [comment] 2019-01-15 20:22
I confirm same behavior, triggered by the same steps as reported. 

It's not possible to export a 'suspect' note because the exports are empty, and there's no pattern to the behavior. I've had it happen when editing anything from text-only notes to notes filled with images and formatting -- the only consistent behavior is that it happens when editing in standalone windows.

Is there a way to increase logging from the app? I wasn't able to find anything in OSX logs with the UUID of the affected notes

**Comment by waz0wski** [comment] 2019-01-15 20:48
I can consistently get this behavior to happen if I move a note to a different notebook while editing in an external window. Maybe this is related to #489 ? 

1. create new note from main ui via hotkey cmd-n
1. create single cell in note with text 'test'
1. in the external note window, move note to another notebook
1. any further edits to the note are lost, cannot preview, export, etc

This test was done on a brand-new, local library and note.

**Comment by ylian** [comment] 2019-01-15 20:57
@waz0wski I can reproduce the bug. Thanks a lot. Will fix in the next update.

**Comment by PatrickF1** [comment] 2019-01-15 22:49
Thanks waz0wski! Can't wait to see this fixed. This bug has bitten me twice
now!

**Comment by palme1337** [comment] 2019-01-21 19:16
This is a VERY nasty bug. I've also lost about an hours worth of work and I thought I lost my whole library as well. Had to restore from my backup. Is there a release scheduled to fix this?

**Comment by ylian** [comment] 2019-01-21 19:44
@palme1337 This will be fixed in 3.2.4, which will come out this week.

**Comment by ylian** [comment] 2019-01-29 06:39
Fixed in 3.2.4.

**Closed as completed by ylian** 2019-01-29 06:39 UTC
Labels: scheduled for release
