### ISSUE TITLE
Couldn’t switch a cell to “Markdown” type

### ISSUE THREAD

**Issue by renfeisong** [HappenApps/Quiver#248] opened 2015-11-19 13:11 UTC
How to reproduce:
1. Open Quiver.
2. Click the + button in the middle column to add a new note.
3. Select the automatically created cell (which is a text cell by default).
4. Click the cell type selector and choose “Markdown Cell.”
5. Type some content in that cell, and you'll find that it is still a text cell.

<img width="339" alt="screen shot 2015-11-19 at 9 08 35 pm" src="https://cloud.githubusercontent.com/assets/4545784/11271591/eef0a7d8-8f01-11e5-9bd3-23cf4f074e85.png">

As a workaround, I have to change it to a Code Cell first and than change it to a Markdown Cell. Seems like a bug to me.

Also I use Markdown 99% of the time and I think it will be nice to be able to set a default cell type other than Text Cell.

**Comment by ylian** [comment] 2015-11-19 21:24
That's weird. I can't reproduce this issue, and I haven't heard anyone else reporting this.

I have a hunch that the app might not have been installed properly. Were you using a beta version before? Sometimes if you overwrite an app in the Applications folder, it keeps some old files around. Please delete Quiver from the Applications folder, then install from Mac AppStore again.

Also, there is a way to set the default cell type. Go to Preferences > General:

![screen shot 2015-11-19 at 4 24 41 pm](https://cloud.githubusercontent.com/assets/984895/11284849/0f2a8852-8eda-11e5-85d2-42b22e765e41.png)

**Comment by renfeisong** [comment] 2015-11-20 01:03
That's wired, because after restarting Quiver this problem disappeared. Also thanks a lot for the tip about setting a default cell type! Sorry I overlooked that.

P.S I've never installed a beta version before.

**Comment by ylian** [comment] 2015-11-20 01:29
Closing this for now. Please reopen if it happens again.

**Closed as completed by ylian** 2015-11-20 01:29 UTC
