### ISSUE TITLE
[Feature Request] Option to allow nested Notebooks

### ISSUE THREAD

**Issue by justnealpatel** [HappenApps/Quiver#530] opened 2016-03-23 16:53 UTC
Although the app is very concise with organization, it would be helpful to better organize notebooks within other notebooks.

Programming Languages (notebook)
      C++ (notebook)
      Java (notebook)
      other notebooks

**Comment by nikivdev** [comment] 2016-03-23 19:18
It has been said that such a feature is coming. I am also really waiting for it but I suppose Lian is focusing on the iOS app currently.

**Comment by ylian** [comment] 2016-03-23 19:30
Duplicate of #2.

**Closed as completed by ylian** 2016-03-23 19:30 UTC
