### ISSUE TITLE
Bug: Spellcheck broken

### ISSUE THREAD

**Issue by 0xCA5E** [HappenApps/Quiver#187] opened 2015-09-20 20:11 UTC
It would be very nice to have the option for spelling to be checked as I type. I noticed there is an option to check the document for spelling errors but it doesn't seem to work. 

`Edit > Spelling and Grammer > Check Document Now`

**Comment by ylian** [comment] 2015-09-20 20:11
In Markdown cells?

**Comment by ylian** [comment] 2015-11-17 18:51
Duplicate of #89.

**Closed as completed by ylian** 2015-11-17 18:51 UTC
