### ISSUE TITLE
[Suggestion] - Mobile app

### ISSUE THREAD

**Issue by bborysenko** [HappenApps/Quiver#280] opened 2015-12-04 13:27 UTC
Quiver has almost all functions that I need to move from Evernote, but what I really missing - is a mobile app.

**Comment by ylian** [comment] 2015-12-04 13:49
Duplicate of https://github.com/HappenApps/Quiver/issues/207.

iOS beta testing starts early January. You can sign up here: http://eepurl.com/bItzIv

**Closed as completed by ylian** 2015-12-04 13:49 UTC

**Comment by ghost** [comment] 2016-01-29 07:15
Hi, I was wondering if maybe the iOS beta testing would start this month?

**Comment by ylian** [comment] 2016-01-29 13:23
@liweijian Getting close. Please be patient. :)

**Comment by pelted** [comment] 2016-06-30 18:00
Five months have passed, are customers any closer to having and iOS app?

**Comment by ylian** [comment] 2016-06-30 19:01
@pelted The iOS beta has been out for a few months.
