### ISSUE TITLE
The first line of a code block in a Markdown Cell is incorrectly indented.

### ISSUE THREAD

**Issue by cdeyoung** [HappenApps/Quiver#62] opened 2015-03-08 17:36 UTC
When typing this code block in a Markdown Cell:

```
output line 1
output line 2
output line 3
```

I would expect the output in both Preview and Presentation modes to be:

output line 1
output line 2
output line 3

However, Quiver is inserting a space before the first line, like this:

_output line 1
output line 2
output line 3

It would be nice if the output didn't have extraneous spaces prepended to it.

**Comment by ylian** [comment] 2015-03-08 18:23
Thanks for reporting the bug. Yes, I can reproduce this issue with a code block inside a Markdown cell. I am a bit surprised to see this, but will fix.

**Comment by zunayed** [comment] 2015-03-17 17:02
Also seeing this issue

**Comment by ylian** [comment] 2015-03-25 02:28
Fixed in v2.1.3b3.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b3.zip

**Comment by cdeyoung** [comment] 2015-03-25 03:35
Excellent!  Thank you.

Clinton De Young

**Comment by zunayed** [comment] 2015-03-25 17:47
Works for me as well! Thanks!

**Comment by ylian** [comment] 2015-11-17 13:25
This is implemented in Quiver 3.0, released today.

**Closed as completed by ylian** 2015-11-17 13:25 UTC
Labels: scheduled for release
