### ISSUE TITLE
Lost markdown markups after converting to plain text

### ISSUE THREAD

**Issue by xg-wang** [HappenApps/Quiver#288] opened 2015-12-06 02:29 UTC
Markdown cells convert to plain text cell can remain the markdown style, but converting back to markdown cell would lost the markups.

**Comment by ylian** [comment] 2015-12-06 02:30
Example? In general the Markdown converter is quite good.

**Comment by xg-wang** [comment] 2015-12-06 02:34
Sorry, the issue occurs when markdown cell converting to plain text cell then code cell then converting to markdown cell again. Normally nobody would do so, I was just tried the effect.

**Comment by ylian** [comment] 2015-12-06 02:36
Oh I see. That's expected. From text cell to code cell, only text content is kept. But from text cell to Markdown cell, the Markdown converter is used and generally works well (for simple formats, not messy HTML).

**Comment by ylian** [comment] 2015-12-06 02:36
I will close this since it's not a bug.

**Closed as completed by ylian** 2015-12-06 02:36 UTC
