### ISSUE TITLE
markdown and code section error

### ISSUE THREAD

**Issue by stevejordi** [HappenApps/Quiver#122] opened 2015-06-01 19:49 UTC
Hi,
Just wanted to know why the code section in markdown introduces a space on the first line before the firs character? This makes it unaligned against following lines.
Examples of code fencing, code marking and code indent with 4 spaces...
- markdown syntax

![markdown text](https://cloud.githubusercontent.com/assets/12702562/7921714/ac3fd188-08a7-11e5-9c84-32bfd591846b.png) 
- markdown rendering

![rendering result](https://cloud.githubusercontent.com/assets/12702562/7921716/af9c6ba2-08a7-11e5-8f09-b6fffa145a4b.png)

**Comment by ylian** [comment] 2015-06-01 23:06
Duplicate of #62. Please use the beta build in that ticket for now. This is scheduled for release in the next update.

**Closed as completed by ylian** 2015-06-01 23:06 UTC
