### ISSUE TITLE
VIM模式替换空格的问题

### ISSUE THREAD

**Issue by leion8310** [HappenApps/Quiver#579] opened 2016-05-09 09:23 UTC
Vim模式中随便选择一段文字，按下R键后，再按空格（本意是把选中的文字替换成空格），结果被选中的那段问题替换成了space字符

![qq20160509-0 2x](https://cloud.githubusercontent.com/assets/6077436/15108788/7c84c9f0-160a-11e6-9455-4db370b1fe52.png)
![qq20160509-1 2x2](https://cloud.githubusercontent.com/assets/6077436/15108819/aa63c196-160a-11e6-9412-51380f3a94cd.png)

**Comment by ylian** [comment] 2016-05-10 11:46
Fixed in 3.0.2. Released today.

**Closed as completed by ylian** 2016-05-10 11:46 UTC

**Comment by shajiquan** [comment] 2016-05-13 01:35
Released? Haven't received any updates in App Store.

**Comment by kadoyau** [comment] 2016-05-13 01:45
It released. I just download it in App Store.

**Comment by shajiquan** [comment] 2016-05-13 03:03
@kadoyau Yes I just get it now. The problem is I can't see any update in App Store's Updates page.

**Comment by shajiquan** [comment] 2016-05-13 03:06
Reinstalled Quiver from App Store, resolved.
