### ISSUE TITLE
Manual Sort No Longer Works

### ISSUE THREAD

**Issue by fpakay** [HappenApps/Quiver#1007] opened 2017-11-22 14:53 UTC
When I manually sort my list, it no longer stays sorted the way I want.

**Comment by TheFriendlyCoder** [comment] 2017-12-18 14:12
I too noticed this problem in the latest release. The easiest way I've found to reproduce the problem is as follows:

1. Set a notebook to "Sort Manually"
2. re-order the tasks as desired
3. Click the "+" button to add a new note to the notebook
4. Check the ordering of the other notes in the notebook - the order has changed

From what I can tell, adding a new note to a notebook causes the other notes in the book to sort based on date created even though the drop-down for selecting the sort order still says "Sort Manually". There doesn't seem to be any easy way afterwards to revert the behavior to retreive your original sort order, thus effectively rendering the manual sort order useless.

It would be of great benefit if this could be fixed sooner rather than later.

**Comment by TheFriendlyCoder** [comment] 2017-12-18 14:15
Correction: I believe the "overridden" sort order may actually be in reverse chronological order based on creation date ... either way, the manual sort order gets messed up.

**Comment by fpakay** [comment] 2017-12-18 14:15
Almost 4 weeks and no comment from the author. Very surprising...

**Comment by TheFriendlyCoder** [comment] 2017-12-18 14:28
I just found this other issue which essentially is the same as this one, but was created back in March:

https://github.com/HappenApps/Quiver/issues/804

This is worrysome. :(

**Comment by TheFriendlyCoder** [comment] 2017-12-18 14:28
> Keep this ticket open. I will address this as part of the data model revamp.

Copied this from the linked issue ... it looks like the "fix" may involve some significant implementation changes from the sounds of it. :(

**Comment by fpakay** [comment] 2017-12-18 14:29
I wish I could get the old version back...

**Comment by TheFriendlyCoder** [comment] 2017-12-18 14:33
Wow - I totally messed up that earlier link. Here's the one I meant to share:

https://github.com/HappenApps/Quiver/issues/1025

**Comment by TheFriendlyCoder** [comment] 2017-12-18 14:34
For reference, I just recently purchased Quiver and one thing I'd like to do is sort my notes by "priority" to be able to construct simple todo-lists for myself and manual sorting is essential to this workflow. This is an important feature for me so if this could be fixed sooner rather than later I would greatly appreciate it.

**Comment by ylian** [comment] 2017-12-18 23:48
Just submitted 3.1.2 that fixes this issue. Should be available for download within a day.

**Comment by ylian** [comment] 2017-12-19 19:38
Fixed in 3.1.2.

**Closed as completed by ylian** 2017-12-19 19:38 UTC
Labels: scheduled for release
