### ISSUE TITLE
When I change notebooks, the app didn't change note.

### ISSUE THREAD

**Issue by letswritetw** [HappenApps/Quiver#1201] opened 2018-11-26 04:31 UTC
I update to Version3.2 today, and then I can not change note when I change notebooks, like this：
[bug demo video](https://youtu.be/erW78Q_ieSY)

**Comment by edding** [comment] 2018-11-26 05:57
Having the same issue here. Also I found sometimes the editing window just freeze there.

**Comment by jinphen** [comment] 2018-11-26 08:17
+1

**Comment by ylian** [comment] 2018-11-26 08:35
Investigating.

**Comment by ylian** [comment] 2018-11-26 08:38
Might have to do with the custom theme you installed. Which theme is it?

**Comment by ylian** [comment] 2018-11-26 08:40
Guess it's this one: Orange Dark theme. Testing.

**Comment by ylian** [comment] 2018-11-26 08:42
Nope. That's not it. Possible to send me your Quiver library? If no sensitive information in it. Email: ylian@happenapps.com

**Comment by lctrcl** [comment] 2018-11-26 08:45
Can confirm that this is what I have after update as well, no custom themes.

**Comment by letswritetw** [comment] 2018-11-26 08:55
> Nope. That's not it. Possible to send me your Quiver library? If no sensitive information in it. Email: [ylian@happenapps.com](mailto:ylian@happenapps.com)

My library are save in dropbox. I'll send you the url to your email.

I find something, when I copy library and save it as new file, then open the new library, everything is back to normal. It's can change note again.

**Comment by ylian** [comment] 2018-11-26 09:02
@auguston Thanks for sending me your Quiver library. I can open the library and switch notebooks, so it looks like an issue with the initial migration. Keep investigating...

**Comment by ylian** [comment] 2018-11-26 09:08
@auguston 
Aha, found something. Some of your notebook names are lowercased and some uppercased. That might have caused the problem during the initial migration.

**Comment by jinphen** [comment] 2018-11-26 09:09
when i move out Quiver library from icloud, it works. but move back to icloud, it show bugs.

**Comment by letswritetw** [comment] 2018-11-26 09:20
> @auguston
> Aha, found something. Some of your notebook names are lowercased and some uppercased. That might have caused the problem during the initial migration.

I change library name "Quiver.qvlibrary" to "quiver.qvlibrary", also work.
My notebooks almost use chinese name, so I change library name first.

**Comment by ylian** [comment] 2018-11-26 09:31
Yep, I am confident I found the culprit. The reason is a tiny renaming I did to the sortKey from "created_at" to "createdAt", but I forgot to convert that during the initial migration. So if you have set custom sort orders of a notebook to created_at or updated_at before, after initial migration, you will run into this bug.

This can be easily fixed on my end. Will confirm the fix with more users, and push it out right away.

**Comment by ylian** [comment] 2018-11-26 09:54
Tentatively stopped the Quiver 3.2 rollout. Submitting 3.2.1 right now.

**Comment by ylian** [comment] 2018-11-26 09:58
The build I posted a few minutes ago is not a complete fix. Will post another one here shortly.

**Comment by ylian** [comment] 2018-11-26 11:18
Submitted 3.2.1 build 178 with the proper fix.

In the meantime, if you are experiencing this bug, you can use this build:

https://www.dropbox.com/s/ml0mdwsvea6diw2/Quiver%203.2.1%20Build%20178.zip?dl=0

**Comment by ewadegam** [comment] 2018-11-26 20:21
@ylian 3.2.1 build 178 didn't fix it for me. When switching notes in the three pane view, the editor section keeps being empty. After a restart of Quiver it works. As soon as I CMD+W the Quiver wIndow and get back to it afterwards, it's broken.

As in #1203.

**Comment by ylian** [comment] 2018-11-26 20:24
@rebewnitram That's a different bug. Let's continue the discussion in #1203. I haven't yet got enough feedback to figure out that bug, but maybe you can help me.

**Comment by ylian** [comment] 2018-11-26 20:25
@rebewnitram A screenshot or screen recording would be very helpful.

**Comment by ylian** [comment] 2018-11-26 20:26
@rebewnitram Actually I reproduced it! As you said, cmd+w then go back! Appreciate it!

**Comment by ewadegam** [comment] 2018-11-26 20:27
You're welcome.

**Comment by ylian** [comment] 2018-11-27 17:10
Fixed in 3.2.1. Appreciate everyone's help to fix this bug. 👍

**Closed as completed by ylian** 2018-11-27 17:10 UTC
Labels: scheduled for release

**Comment by ylian** [comment] 2018-11-27 17:11
Also please delete the previous builds I sent, and download the official version from the App Store.
