### ISSUE TITLE
Extra blank space at the bottom of rendered code block

### ISSUE THREAD

**Issue by renfeisong** [HappenApps/Quiver#249] opened 2015-11-19 13:37 UTC
The rendered code block of Markdown cell contains a "space" at the bottom that cannot be easily removed. See picture below:

<img width="747" alt="screen shot 2015-11-19 at 9 18 00 pm" src="https://cloud.githubusercontent.com/assets/4545784/11271805/7ef40acc-8f03-11e5-81e1-927d0ffb3a8d.png">

By examining the underlying HTML code I found that there is a `div` tag placed inside of another `code` tag. This is syntactically incorrect because block-level tags cannot be placed under inline tags. I believe this is causing the extra space to appear because if I remove the `code` tag the space also disappears.

As a temporary workaround, I have given the `code` tag a `display:block` (along with my other theme-specific rules). However I think it's nice to have an official and more clean solution.

**Comment by ylian** [comment] 2015-11-19 21:32
I can't reproduce this either. This is what I have:

![screen shot 2015-11-19 at 4 28 59 pm](https://cloud.githubusercontent.com/assets/984895/11284940/b50d6b9a-8eda-11e5-9bdd-ee9ad101fafc.png)

Please delete Quiver from Applications folder and reinstall from the Mac AppStore. As I said in the other ticket, I suspect the app wasn't installed properly.

Also, there is an error in your screenshot. If you could click on that, maybe it will give me some clue.

**Comment by renfeisong** [comment] 2015-11-20 01:13
In fact I believe that your screenshot reproduced exactly what I meant. You can see from the picture that the vertical space between the code block and “some text” is a lot bigger than it should be.

I'm not sure what you meant by _If you could click on that…_; In my screenshot I enabled the `WebKitDeveloperExtras` to inspect the HTML code, if that matters. If you need more information feel free to let me know.

**Comment by ylian** [comment] 2015-11-20 01:16
Oh, I see. I thought there was an extra line _inside_ the code cell.

What I meant was the red error icon: 
![screen shot 2015-11-19 at 8 15 02 pm](https://cloud.githubusercontent.com/assets/984895/11289380/3bac6650-8efa-11e5-8fe5-1b9e5f8c9be7.png)

That indicates a JavaScript error, probably an error that happened earlier. You can click on that red error icon and it will show the error in the console. But that error has nothing to do with this ticket. It might have caused the weird behavior in #248.

**Comment by renfeisong** [comment] 2015-11-20 01:26
The error is gone now. I will let you know if I ever encounter the error in the future. BTW - great app! Nicely done :)

**Comment by ylian** [comment] 2015-11-20 01:29
Yep, the console log is cleared when the app is relaunched. So if weird things happen ago, take a look at the error and let me know. :)

**Comment by ylian** [comment] 2015-11-20 01:33
You are right about the extra space under the code cell. It shouldn't be there. I will fix.

**Comment by ylian** [comment] 2015-11-20 01:35
BTW, I like your app too. :) Maybe we can collaborate on something some day.

**Comment by renfeisong** [comment] 2015-11-20 02:04
Sure, that'll be cool :smile:

**Comment by ylian** [comment] 2016-02-09 01:17
Fixed in 3.0.1.

**Closed as completed by ylian** 2016-02-09 01:17 UTC
Labels: scheduled for release
