### ISSUE TITLE
Quiver app opens with all notes missing

### ISSUE THREAD

**Issue by thiyagu-7** [HappenApps/Quiver#1310] opened 2019-05-04 12:28 UTC
I'm creating this issue as [this](https://github.com/HappenApps/Quiver/issues/309) doesn't seem to be fixed.

Whenever I open Quiver after restarting my machine, none of the notes show up. I have to open quiver and open by double-clicking **Quiver.qvlibrary** on restarts.

Can you at least make sure this is an internal problem and my notes won't be lost.

P.S: I'm using 3.2.4 version and google drive for sync.

**Comment by ylian** [comment] 2019-05-04 15:43
I have figured out the root cause of this issue with the help of a user. The fix is coming out in 3.2.5, within a couple days.

In the meantime, you can reset the cache to work around the bug.

1. Delete the cache file and the search index file:
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/index-v2.dat
2. Double click on your library to open Quiver again.

**Comment by thiyagu-7** [comment] 2019-05-05 03:54
@ylian Thanks for the quick response. Happy it is getting fixed :)

**Comment by ylian** [comment] 2019-05-10 04:57
Fixed in 3.2.5. Please note that 3.2.5 only prevents this from happening again. You still need to run the above instructions to reset the cache since your security bookmark is already invalidated.

**Closed as completed by ylian** 2019-05-10 04:57 UTC
