### ISSUE TITLE
Request: For markdown links, automatically fill in selected text as title

### ISSUE THREAD

**Issue by jafish** [HappenApps/Quiver#509] opened 2016-03-10 21:14 UTC
For example, if I select "link here", then press Command+K, I'd like "link here" to be autofilled in the link title field.

**Comment by ylian** [comment] 2016-03-11 04:00
Duplicate of https://github.com/HappenApps/Quiver/issues/373. Will fix in the next update.

**Closed as completed by ylian** 2016-03-11 04:00 UTC
