### ISSUE TITLE
Touchbar Blinking when Inputting Notes

### ISSUE THREAD

**Issue by eric-kwon** [HappenApps/Quiver#956] opened 2017-09-13 19:33 UTC
When you are typing notes on the Macbook Pro models with the touch bar, the touch bar constantly blinks.

**Comment by zachkirsch** [comment] 2017-09-17 23:05
Seems to be a dupe of #788

**Comment by ylian** [comment] 2017-11-09 08:50
Fixed in 3.1.1.

**Closed as completed by ylian** 2017-11-09 08:50 UTC
